Fix compilation warnings when NDEBUG is set
When NDEBUG is set (-DCMAKE_BUILD_TYPE=Release) and CFLAGS is set to
-Werorr, we get some compilation errors as the following:

rdma-core/libibverbs/neigh.c:378:13: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
     ssize_t rc;

issue: 1155711
Change-Id: Id49a562c85d1de4690489a9be506104656923904
Signed-off-by: Alaa Hleihel <alaa@mellanox.com>