cbuild: Add udev dependency to package list of SuSE Leap
rpmbuild under SUSE requires udev and produces the following errors:

error: Failed build dependencies:
        pkgconfig(udev) is needed by rdma-core-16-0.x86_64

issue: 1155711
Change-Id: Ib695f3f045c50a9e179797f9c3ccc0a9fb5fd02b
Signed-off-by: Alaa Hleihel <alaa@mellanox.com>